In [1]:
import eurostat
import pandas as pd
import plotly.express as px


#Vytvorenie priecikov
import os
cwd = os.getcwd()
from datetime import date, datetime
today = date.today()

os.makedirs('./Vykonnost ekonomiky/', exist_ok=True) 
os.makedirs('./Inflacia/', exist_ok=True)
os.makedirs('./Nezamestnanost/', exist_ok=True) 
os.makedirs('./Fiskalna politika/', exist_ok=True) 
os.makedirs('./Menova politika/', exist_ok=True) 
os.makedirs('./Medzinarodny obchod/', exist_ok=True)
os.makedirs('./Ekonomicky rast a cykkly/', exist_ok=True)
os.makedirs('./Socialno-ekonomicke ukazovatele/', exist_ok=True)

In [2]:
###Hruby domaci produkt per capita
gdp_per_capita = eurostat.get_data_df('nama_10_pc')
gdp_per_capita = gdp_per_capita[(gdp_per_capita['geo\\TIME_PERIOD'].isin(['SK', 'CZ','EU27_2020','EA']) & (gdp_per_capita['na_item'] == 'B1GQ') & (gdp_per_capita['unit'] == 'CP_PPS_EU27_2020_HAB'))]
gdp_per_capita = gdp_per_capita[['unit','na_item', 'geo\\TIME_PERIOD','2007','2008','2009','2010','2011','2012','2013']]
gdp_per_capita['geo\\TIME_PERIOD'] = gdp_per_capita['geo\\TIME_PERIOD'].replace({'EA': 'Oblast Eura','EU27_2020': 'Staty EU'})
gdp_per_capita = gdp_per_capita.rename(columns={'geo\\TIME_PERIOD': 'Krajina', 'na_item': 'Indikator', 'unit' : 'Jednotka'})
gdp_per_capita['Indikator'] = gdp_per_capita['Indikator'].replace({'B1GQ': 'HDP podla trhovych cien'})
gdp_per_capita['Jednotka'] = gdp_per_capita['Jednotka'].replace({'CP_PPS_EU27_2020_HAB': 'PPS per capita'})

display(gdp_per_capita.tail(100))

gdp_1 = gdp_per_capita.melt(
    id_vars=['Krajina'],
    value_vars=['2007','2008','2009','2010','2011','2012','2013'],
    var_name='Year',
    value_name='GDP_per_capita')

fig = px.line(
    gdp_1,
    x='Year',
    y='GDP_per_capita',
    color='Krajina',
    markers=True,
    text='GDP_per_capita', 
    title='HDP per capita – SK vs CZ vs Oblast eura vs Staty EU (2007–2013)',
    labels={'GDP_per_capita': 'HDP per capita (PPS)', 'Year': 'Rok'}
)

fig.for_each_trace(lambda t: t.update(
    mode='lines+markers+text',
    line=dict(width=4),
    marker=dict(size=12, line=dict(width=2, color='white')),
    textposition='top center',
    texttemplate='%{text:.1f}'
))

fig.update_layout(template='simple_white', hovermode=False)
fig.show()


file_name = f'./Vykonnost ekonomiky/gdp_per_capita_{today}.csv'
#gdp_per_capita.to_csv(os.getcwd() + r'.\Vykonnost ekonomiky\gdp_per_capita_{}.csv'.format(today),index=True, header=True, encoding="utf-8-sig")

,Jednotka,Indikator,Krajina,2007,2008,2009,2010,2011,2012,2013
3289,PPS per capita,HDP podla trhovych cien,CZ,20692.0,21587.3,20826.8,21227.8,21786.4,21767.6,22410.8
3292,PPS per capita,HDP podla trhovych cien,Oblast Eura,27887.7,28385.1,26820.5,27628.3,28291.3,28275.1,28569.3
3299,PPS per capita,HDP podla trhovych cien,Staty EU,24679.2,25392.0,24226.7,25095.1,25876.8,25979.8,26253.5
3321,PPS per capita,HDP podla trhovych cien,SK,16696.1,18312.5,17321.0,19079.5,19526.5,19960.4,20266.6

In [3]:
###Celkovy hruby domaci produkt na krajinu

gdp_gross = eurostat.get_data_df('nama_10_gdp')
gdp_gross = gdp_gross[(gdp_gross['geo\\TIME_PERIOD'].isin(['SK', 'CZ','EU27_2020','EA']) & (gdp_gross['na_item'] == 'B1G') & (gdp_gross['unit'] == 'CP_MEUR'))]
gdp_gross = gdp_gross[['unit', 'geo\\TIME_PERIOD','2007','2008','2009','2010','2011','2012','2013']]
gdp_gross['geo\\TIME_PERIOD'] = gdp_gross['geo\\TIME_PERIOD'].replace({ 'EA': 'Oblast Eura','EU27_2020': 'Staty EU'})
gdp_gross = gdp_gross.rename(columns={'geo\\TIME_PERIOD': 'Krajina', 'unit' : 'Jednotka'})
gdp_gross['Jednotka'] = gdp_gross['Jednotka'].replace({'CP_MEUR': 'Sucasne ceny v mil. Eur'})


display(gdp_gross.tail(100))

gdp_2 = gdp_gross.melt(
    id_vars=['Krajina'],
    value_vars=['2007','2008','2009','2010','2011','2012','2013'],
    var_name='Year',
    value_name='Gross_GDP')

fig = px.line(
    gdp_2,
    x='Year',
    y='Gross_GDP',
    color='Krajina',
    markers=True,
    text='Gross_GDP',
    title='Hrube HDP – SK vs CZ (2007–2013)',
    labels={'Gross_GDP': 'Hrube HDP', 'Year': 'Rok'}
)

fig.for_each_trace(lambda t: t.update(
    mode='lines+markers+text',
    line=dict(width=4),
    marker=dict(size=12, line=dict(width=2, color='white')),
    textposition='top center',
    texttemplate='%{text:.1f}'  # 1 decimal
))

fig.update_layout(template='simple_white', hovermode=False)
fig.show()

file_name = f'./Vykonnost ekonomiky/gross_gdp_{today}.csv'
gdp_gross.to_csv(os.getcwd() + r'.\Vykonnost ekonomiky\gross_gdp_{}.csv'.format(today),index=True, header=True, encoding="utf-8-sig")

,Jednotka,Krajina,2007,2008,2009,2010,2011,2012,2013
13668,Sucasne ceny v mil. Eur,CZ,125780.7,146823.9,135019.6,144502.8,150546.4,147400.9,143926.7
13671,Sucasne ceny v mil. Eur,Oblast Eura,8305630.2,8560396.4,8352911.6,8562140.0,8801720.3,8820585.0,8902595.0
13678,Sucasne ceny v mil. Eur,Staty EU,9618990.8,9969685.0,9565406.4,9887370.1,10192240.6,10240555.4,10343438.8
13701,Sucasne ceny v mil. Eur,SK,50472.1,59534.7,57953.2,62293.1,64503.5,67018.9,67552.6

In [4]:
inflacia_hicp = eurostat.get_data_df('prc_hicp_aind')
inflacia_hicp = inflacia_hicp[(inflacia_hicp['geo\\TIME_PERIOD'].isin(['SK', 'CZ','EU27_2020','EA20']) & (inflacia_hicp['unit'] == 'RCH_A_AVG') & (inflacia_hicp['coicop'] == 'CP00'))]
inflacia_hicp = inflacia_hicp[['unit','coicop', 'geo\\TIME_PERIOD','2007','2008','2009','2010','2011','2012','2013']]

inflacia_hicp['geo\\TIME_PERIOD'] = inflacia_hicp['geo\\TIME_PERIOD'].replace({ 'EA20': 'Oblast Eura','EU27_2020': 'Staty EU'})
inflacia_hicp  = inflacia_hicp .rename(columns={'geo\\TIME_PERIOD': 'Krajina', 'unit' : 'Jednotka', 'coicop' : 'Polozky'})
inflacia_hicp ['Jednotka'] = inflacia_hicp ['Jednotka'].replace({'RCH_A_AVG': 'Rocna zmena v %'})
inflacia_hicp ['Polozky'] = inflacia_hicp ['Polozky'].replace({'CP00': 'Vsetky polozky'})

display(inflacia_hicp.tail(100))

infl_hicp = inflacia_hicp.melt(
    id_vars=['Krajina'],
    value_vars=['2007','2008','2009','2010','2011','2012','2013'],
    var_name='Year',
    value_name='Inflacia_perc')

fig = px.line(
    infl_hicp,
    x='Year',
    y='Inflacia_perc',
    color='Krajina',
    markers=True,
    text='Inflacia_perc',
    title='Inflacia HICP pre vsetky polozky – SK vs CZ (2007–2013)',
    labels={'Inflacia_perc': 'Inflacia v %', 'Year': 'Rok'}
)

fig.for_each_trace(lambda t: t.update(
    mode='lines+markers+text',
    line=dict(width=4),
    marker=dict(size=12, line=dict(width=2, color='white')),
    textposition='top center',
    texttemplate='%{text:.1f}'  # 1 decimal
))

fig.update_layout(template='simple_white', hovermode=False)
fig.show()

file_name = f'./Inflacia/inflacia_hicp_{today}.csv'
inflacia_hicp.to_csv(os.getcwd() + r'.\Inflacia\inflacia_hicp_{}.csv'.format(today),index=True, header=True, encoding="utf-8-sig")

,Jednotka,Polozky,Krajina,2007,2008,2009,2010,2011,2012,2013
17877,Rocna zmena v %,Vsetky polozky,CZ,2.9,6.3,0.6,1.2,2.2,3.5,1.4
17882,Rocna zmena v %,Vsetky polozky,Oblast Eura,2.2,3.4,0.3,1.6,2.7,2.5,1.4
17888,Rocna zmena v %,Vsetky polozky,Staty EU,2.4,3.7,0.8,1.8,2.9,2.6,1.3
17911,Rocna zmena v %,Vsetky polozky,SK,1.9,3.9,0.9,0.7,4.1,3.7,1.5

In [5]:
###Celkova miera nezamestnanosti 
nezamestnanost_celk = eurostat.get_data_df('une_rt_a')
nezamestnanost_celk = nezamestnanost_celk[(nezamestnanost_celk['geo\\TIME_PERIOD'].isin(['SK', 'CZ','EU27_2020','EA20']) & (nezamestnanost_celk['sex'] == 'T') & (nezamestnanost_celk['unit'] == 'PC_ACT') & (nezamestnanost_celk['age'] == 'Y15-74'))]
nezamestnanost_celk = nezamestnanost_celk[['unit','age','sex', 'geo\\TIME_PERIOD','2007','2008','2009','2010','2011','2012','2013']]
nezamestnanost_celk['geo\\TIME_PERIOD'] = nezamestnanost_celk['geo\\TIME_PERIOD'].replace({ 'EA20': 'Oblast Eura','EU27_2020': 'Staty EU'})

nezamestnanost_celk = nezamestnanost_celk.rename(columns={'geo\\TIME_PERIOD': 'Krajina', 'unit' : 'Jednotka', 'age' : 'Vekova skupina', 'sex' : 'Pohlavie'})
nezamestnanost_celk['Jednotka'] = nezamestnanost_celk['Jednotka'].replace({'PC_ACT': '% z pracujucej populacie'})
nezamestnanost_celk['Pohlavie'] = nezamestnanost_celk['Pohlavie'].replace({'T': 'Vsetky pohlavia'})
nezamestnanost_celk['Vekova skupina'] = nezamestnanost_celk['Vekova skupina'].replace({'Y15-74': '15-74 Rokov'})

display(nezamestnanost_celk.tail(100))

nezamest_total = nezamestnanost_celk.melt(
    id_vars=['Krajina'],
    value_vars=['2007','2008','2009','2010','2011','2012','2013'],
    var_name='Year',
    value_name='Nezamestnanost_celkova')

fig = px.line(
    nezamest_total,
    x='Year',
    y='Nezamestnanost_celkova',
    color='Krajina',
    markers=True,
    text='Nezamestnanost_celkova',
    title='Celkova miera nezamestnanosti v % z pracujucej populacie – SK vs CZ (2007–2013)',
    labels={'Nezamestnanost_celkova': 'Nezamestnanost v %', 'Year': 'Rok'}
)

fig.for_each_trace(lambda t: t.update(
    mode='lines+markers+text',
    line=dict(width=4),
    marker=dict(size=12, line=dict(width=2, color='white')),
    textposition='top center',
    texttemplate='%{text:.1f}'  # 1 decimal
))

fig.update_layout(template='simple_white', hovermode=False)
fig.show()

file_name = f'./Nezamestnanost/nezamestnanost_celk_{today}.csv'
nezamestnanost_celk.to_csv(os.getcwd() + r'.\Nezamestnanost\nezamestnanost_celk_{}.csv'.format(today),index=True, header=True, encoding="utf-8-sig")

,Jednotka,Vekova skupina,Pohlavie,Krajina,2007,2008,2009,2010,2011,2012,2013
746,% z pracujucej populacie,15-74 Rokov,Vsetky pohlavia,CZ,NaN,NaN,6.7,7.3,6.7,7.0,7.0
749,% z pracujucej populacie,15-74 Rokov,Vsetky pohlavia,Oblast Eura,NaN,NaN,9.7,10.3,10.3,11.5,12.2
753,% z pracujucej populacie,15-74 Rokov,Vsetky pohlavia,Staty EU,NaN,NaN,9.3,10.1,10.1,11.1,11.6
775,% z pracujucej populacie,15-74 Rokov,Vsetky pohlavia,SK,NaN,NaN,12.0,14.3,13.5,13.9,14.1

In [6]:
###Miera nezamestnanosti zien 
nezamestnanost_zien = eurostat.get_data_df('une_rt_a')
nezamestnanost_zien = nezamestnanost_zien[(nezamestnanost_zien['geo\\TIME_PERIOD'].isin(['SK', 'CZ','EU27_2020','EA20']) & (nezamestnanost_zien['sex'] == 'F') & (nezamestnanost_zien['unit'] == 'PC_ACT') & (nezamestnanost_zien['age'] == 'Y15-74'))]
nezamestnanost_zien = nezamestnanost_zien[['unit','age','sex', 'geo\\TIME_PERIOD','2007','2008','2009','2010','2011','2012','2013']]
nezamestnanost_zien['geo\\TIME_PERIOD'] = nezamestnanost_zien['geo\\TIME_PERIOD'].replace({ 'EA20': 'Oblast Eura','EU27_2020': 'Staty EU'})

nezamestnanost_zien = nezamestnanost_zien.rename(columns={'geo\\TIME_PERIOD': 'Krajina', 'unit' : 'Jednotka', 'age' : 'Vekova skupina', 'sex' : 'Pohlavie'})
nezamestnanost_zien['Jednotka'] = nezamestnanost_zien['Jednotka'].replace({'PC_ACT': '% z pracujucej populacie'})
nezamestnanost_zien['Pohlavie'] = nezamestnanost_zien['Pohlavie'].replace({'F': 'Zeny'})
nezamestnanost_zien['Vekova skupina'] = nezamestnanost_zien['Vekova skupina'].replace({'Y15-74': '15-74 Rokov'})

display(nezamestnanost_zien.tail(100))

nezamest_fem = nezamestnanost_zien.melt(
    id_vars=['Krajina'],
    value_vars=['2007','2008','2009','2010','2011','2012','2013'],
    var_name='Year',
    value_name='Nezamestnanost_zien')

fig = px.line(
    nezamest_fem,
    x='Year',
    y='Nezamestnanost_zien',
    color='Krajina',
    markers=True,
    text='Nezamestnanost_zien',
    title='Nezamestnanost zien z pracujucej populacie v% – SK vs CZ (2007–2013)',
    labels={'Nezamestnanost_zien': 'Nezamestnanost zien v %', 'Year': 'Rok'}
)

fig.for_each_trace(lambda t: t.update(
    mode='lines+markers+text',
    line=dict(width=4),
    marker=dict(size=12, line=dict(width=2, color='white')),
    textposition='top center',
    texttemplate='%{text:.1f}'  # 1 decimal
))

fig.update_layout(template='simple_white', hovermode=False)
fig.show()

file_name = f'./Nezamestnanost/nezamestnanost_zien_{today}.csv'
nezamestnanost_zien.to_csv(os.getcwd() + r'.\Nezamestnanost\nezamestnanost_zien_{}.csv'.format(today),index=True, header=True, encoding="utf-8-sig")

,Jednotka,Vekova skupina,Pohlavie,Krajina,2007,2008,2009,2010,2011,2012,2013
672,% z pracujucej populacie,15-74 Rokov,Zeny,CZ,NaN,NaN,7.7,8.5,7.9,8.2,8.3
675,% z pracujucej populacie,15-74 Rokov,Zeny,Oblast Eura,NaN,NaN,9.8,10.4,10.5,11.7,12.3
679,% z pracujucej populacie,15-74 Rokov,Zeny,Staty EU,NaN,NaN,9.5,10.2,10.3,11.2,11.7
701,% z pracujucej populacie,15-74 Rokov,Zeny,SK,NaN,NaN,13.0,14.8,13.8,14.7,14.7

In [ ]:
###Miera nezamestnanosti mladych 15-24 rokov
nezamestnanost_mladych = eurostat.get_data_df('une_rt_a')
nezamestnanost_mladych = nezamestnanost_mladych[(nezamestnanost_mladych['geo\\TIME_PERIOD'].isin(['SK', 'CZ','EU27_2020','EA20']) & (nezamestnanost_mladych['sex'] == 'T') & (nezamestnanost_mladych['unit'] == 'PC_ACT') & (nezamestnanost_mladych['age'] == 'Y15-24'))]
nezamestnanost_mladych = nezamestnanost_mladych[['unit','age','sex', 'geo\\TIME_PERIOD','2007','2008','2009','2010','2011','2012','2013']]
nezamestnanost_mladych['geo\\TIME_PERIOD'] = nezamestnanost_mladych['geo\\TIME_PERIOD'].replace({ 'EA20': 'Oblast Eura','EU27_2020': 'Staty EU'})

nezamestnanost_mladych = nezamestnanost_mladych.rename(columns={'geo\\TIME_PERIOD': 'Krajina', 'unit' : 'Jednotka', 'age' : 'Vekova skupina', 'sex' : 'Pohlavie'})
nezamestnanost_mladych['Jednotka'] = nezamestnanost_mladych['Jednotka'].replace({'PC_ACT': '% z pracujucej populacie'})
nezamestnanost_mladych['Pohlavie'] = nezamestnanost_mladych['Pohlavie'].replace({'T': 'Vsetky pohlavia'})
nezamestnanost_mladych['Vekova skupina'] = nezamestnanost_mladych['Vekova skupina'].replace({'Y15-24': '15-24 Rokov'})

display(nezamestnanost_mladych.tail(100))

nezamest_yng = nezamestnanost_mladych.melt(
    id_vars=['Krajina'],
    value_vars=['2007','2008','2009','2010','2011','2012','2013'],
    var_name='Year',
    value_name='Nezamestnanost_zien')

fig = px.line(
    nezamest_yng,
    x='Year',
    y='Nezamestnanost_zien',
    color='Krajina',
    markers=True,
    text='Nezamestnanost_zien',
    title='Nezamestnanost mladych – SK vs CZ (2007–2013)',
    labels={'Nezamestnanost_zien': 'Nezamestnanost mladych vo veku 15-24 v %', 'Year': 'Rok'}
)

fig.for_each_trace(lambda t: t.update(
    mode='lines+markers+text',
    line=dict(width=4),
    marker=dict(size=12, line=dict(width=2, color='white')),
    textposition='top center',
    texttemplate='%{text:.1f}'  # 1 decimal
))

fig.update_layout(template='simple_white', hovermode=False)
fig.show()

file_name = f'./Nezamestnanost/nezamestnanost_mladych_{today}.csv'
nezamestnanost_mladych.to_csv(os.getcwd() + r'.\Nezamestnanost\nezamestnanost_mladych_{}.csv'.format(today),index=True, header=True, encoding="utf-8-sig")

,Jednotka,Vekova skupina,Pohlavie,Krajina,2007,2008,2009,2010,2011,2012,2013
80,% z pracujucej populacie,15-24 Rokov,Vsetky pohlavia,CZ,NaN,NaN,16.6,18.3,18.1,19.5,19.0
83,% z pracujucej populacie,15-24 Rokov,Vsetky pohlavia,Oblast Eura,NaN,NaN,21.3,22.1,22.1,24.3,25.2
87,% z pracujucej populacie,15-24 Rokov,Vsetky pohlavia,Staty EU,NaN,NaN,21.2,22.4,22.5,24.4,25.2
109,% z pracujucej populacie,15-24 Rokov,Vsetky pohlavia,SK,NaN,NaN,28.5,34.9,34.8,35.3,34.9