In [1]:
import eurostat
import pandas as pd
import plotly.express as px


#Vytvorenie priecikov
import os
cwd = os.getcwd()
from datetime import date, datetime
today = date.today()

os.makedirs('./Vykonnost ekonomiky/', exist_ok=True) 
os.makedirs('./Inflacia/', exist_ok=True)
os.makedirs('./Nezamestnanost/', exist_ok=True) 
os.makedirs('./Fiskalna politika/', exist_ok=True) 
os.makedirs('./Menova politika/', exist_ok=True) 
os.makedirs('./Medzinarodny obchod/', exist_ok=True)
os.makedirs('./Ekonomicky rast a cykkly/', exist_ok=True)
os.makedirs('./Socialno-ekonomicke ukazovatele/', exist_ok=True)

In [2]:
###Hruby domaci produkt per capita
gdp_per_capita = eurostat.get_data_df('nama_10_pc')
gdp_per_capita = gdp_per_capita[(gdp_per_capita['geo\\TIME_PERIOD'].isin(['SK', 'CZ','EU27_2020','EA']) & (gdp_per_capita['na_item'] == 'B1GQ') & (gdp_per_capita['unit'] == 'CP_PPS_EU27_2020_HAB'))]
gdp_per_capita = gdp_per_capita[['unit','na_item', 'geo\\TIME_PERIOD','2007','2008','2009','2010','2011','2012','2013']]
gdp_per_capita['geo\\TIME_PERIOD'] = gdp_per_capita['geo\\TIME_PERIOD'].replace({'EA': 'Oblast Eura','EU27_2020': 'Staty EU'})
gdp_per_capita = gdp_per_capita.rename(columns={'geo\\TIME_PERIOD': 'Krajina', 'na_item': 'Indikator', 'unit' : 'Jednotka'})
gdp_per_capita['Indikator'] = gdp_per_capita['Indikator'].replace({'B1GQ': 'HDP podla trhovych cien'})
gdp_per_capita['Jednotka'] = gdp_per_capita['Jednotka'].replace({'CP_PPS_EU27_2020_HAB': 'PPS per capita'})

display(gdp_per_capita.tail(100))

gdp_1 = gdp_per_capita.melt(
    id_vars=['Krajina'],
    value_vars=['2007','2008','2009','2010','2011','2012','2013'],
    var_name='Year',
    value_name='GDP_per_capita')

fig = px.line(
    gdp_1,
    x='Year',
    y='GDP_per_capita',
    color='Krajina',
    markers=True,
    text='GDP_per_capita', 
    title='HDP per capita – SK vs CZ vs Oblast eura vs Staty EU (2007–2013)',
    labels={'GDP_per_capita': 'HDP per capita (PPS)', 'Year': 'Rok'}
)

fig.for_each_trace(lambda t: t.update(
    mode='lines+markers+text',
    line=dict(width=4),
    marker=dict(size=12, line=dict(width=2, color='white')),
    textposition='top center',
    texttemplate='%{text:.1f}'
))

fig.update_layout(template='simple_white', hovermode=False)
fig.show()


file_name = f'./Vykonnost ekonomiky/gdp_per_capita_{today}.csv'
#gdp_per_capita.to_csv(os.getcwd() + r'.\Vykonnost ekonomiky\gdp_per_capita_{}.csv'.format(today),index=True, header=True, encoding="utf-8-sig")

,Jednotka,Indikator,Krajina,2007,2008,2009,2010,2011,2012,2013
3289,PPS per capita,HDP podla trhovych cien,CZ,20692.0,21587.3,20826.8,21227.8,21786.4,21767.6,22410.8
3292,PPS per capita,HDP podla trhovych cien,Oblast Eura,27887.7,28385.1,26820.5,27628.3,28291.3,28275.1,28569.3
3299,PPS per capita,HDP podla trhovych cien,Staty EU,24679.2,25392.0,24226.7,25095.1,25876.8,25979.8,26253.5
3321,PPS per capita,HDP podla trhovych cien,SK,16696.1,18312.5,17321.0,19079.5,19526.5,19960.4,20266.6

In [5]:
###Celkovy hruby domaci produkt na krajinu

gdp_gross = eurostat.get_data_df('nama_10_gdp')
gdp_gross = gdp_gross[(gdp_gross['geo\\TIME_PERIOD'].isin(['SK', 'CZ','EU27_2020','EA']) & (gdp_gross['na_item'] == 'B1G') & (gdp_gross['unit'] == 'CP_MEUR'))]
gdp_gross = gdp_gross[['unit', 'geo\\TIME_PERIOD','2007','2008','2009','2010','2011','2012','2013']]
gdp_gross['geo\\TIME_PERIOD'] = gdp_gross['geo\\TIME_PERIOD'].replace({ 'EA': 'Oblast Eura','EU27_2020': 'Staty EU'})
gdp_gross = gdp_gross.rename(columns={'geo\\TIME_PERIOD': 'Krajina', 'unit' : 'Jednotka'})
gdp_gross['Jednotka'] = gdp_gross['Jednotka'].replace({'CP_MEUR': 'Sucasne ceny v mil. Eur'})


display(gdp_gross.tail(100))

gdp_2 = gdp_gross.melt(
    id_vars=['Krajina'],
    value_vars=['2007','2008','2009','2010','2011','2012','2013'],
    var_name='Year',
    value_name='Gross_GDP')

fig = px.line(
    gdp_2,
    x='Year',
    y='Gross_GDP',
    color='Krajina',
    markers=True,
    text='Gross_GDP',
    title='Hrube HDP – SK vs CZ (2007–2013)',
    labels={'Gross_GDP': 'Hrube HDP', 'Year': 'Rok'}
)

fig.for_each_trace(lambda t: t.update(
    mode='lines+markers+text',
    line=dict(width=4),
    marker=dict(size=12, line=dict(width=2, color='white')),
    textposition='top center',
    texttemplate='%{text:.1f}'  # 1 decimal
))

fig.update_layout(template='simple_white', hovermode=False)
fig.show()

file_name = f'./Vykonnost ekonomiky/gross_gdp_{today}.csv'
gdp_gross.to_csv(os.getcwd() + r'.\Vykonnost ekonomiky\gross_gdp_{}.csv'.format(today),index=True, header=True, encoding="utf-8-sig")

,Jednotka,Krajina,2007,2008,2009,2010,2011,2012,2013
13668,Sucasne ceny v mil. Eur,CZ,125780.7,146823.9,135019.6,144502.8,150546.4,147400.9,143926.7
13671,Sucasne ceny v mil. Eur,Oblast Eura,8305630.2,8560396.4,8352911.6,8562140.0,8801720.3,8820585.0,8902595.0
13678,Sucasne ceny v mil. Eur,Staty EU,9618990.8,9969685.0,9565406.4,9887370.1,10192240.6,10240555.4,10343438.8
13701,Sucasne ceny v mil. Eur,SK,50472.1,59534.7,57953.2,62293.1,64503.5,67018.9,67552.6