In [2]:
import eurostat, requests, os
cwd = os.getcwd()

import pandas as pd
import plotly.express as px

import numpy as np

from datetime import datetime
today = datetime.now().strftime('%Y-%m-%d')

from io import StringIO

os.makedirs('./Vykonnost ekonomiky/', exist_ok=True) 
os.makedirs('./Inflacia/', exist_ok=True)
os.makedirs('./Nezamestnanost/', exist_ok=True) 
os.makedirs('./Fiskalna politika/', exist_ok=True) 
os.makedirs('./Menova politika/', exist_ok=True) 
os.makedirs('./Medzinarodny obchod/', exist_ok=True)
os.makedirs('./Ekonomicky rast a cykkly/', exist_ok=True)
os.makedirs('./Socialno-ekonomicke ukazovatele/', exist_ok=True)
os.makedirs('./Medzinarodny obchod/', exist_ok=True)
os.makedirs('./Menova politika/', exist_ok=True)

In [2]:
###Hruby domaci produkt per capita
gdp_per_capita = eurostat.get_data_df('nama_10_pc')
gdp_per_capita = gdp_per_capita[(gdp_per_capita['geo\\TIME_PERIOD'].isin(['SK', 'CZ','EU27_2020','EA']) & (gdp_per_capita['na_item'] == 'B1GQ') & (gdp_per_capita['unit'] == 'CP_PPS_EU27_2020_HAB'))]
gdp_per_capita = gdp_per_capita[['unit','na_item', 'geo\\TIME_PERIOD','2007','2008','2009','2010','2011','2012','2013']]
gdp_per_capita['geo\\TIME_PERIOD'] = gdp_per_capita['geo\\TIME_PERIOD'].replace({'EA': 'Oblast Eura','EU27_2020': 'Staty EU'})
gdp_per_capita = gdp_per_capita.rename(columns={'geo\\TIME_PERIOD': 'Krajina', 'na_item': 'Indikator', 'unit' : 'Jednotka'})
gdp_per_capita['Indikator'] = gdp_per_capita['Indikator'].replace({'B1GQ': 'HDP podla trhovych cien'})
gdp_per_capita['Jednotka'] = gdp_per_capita['Jednotka'].replace({'CP_PPS_EU27_2020_HAB': 'PPS per capita'})

display(gdp_per_capita.tail(100))

gdp_1 = gdp_per_capita.melt(
    id_vars=['Krajina'],
    value_vars=['2007','2008','2009','2010','2011','2012','2013'],
    var_name='Year',
    value_name='GDP_per_capita')

fig = px.line(
    gdp_1,
    x='Year',
    y='GDP_per_capita',
    color='Krajina',
    markers=True,
    text='GDP_per_capita', 
    title='HDP per capita – SK vs CZ vs Oblast eura vs Staty EU (2007–2013)',
    labels={'GDP_per_capita': 'HDP per capita (PPS)', 'Year': 'Rok'}
)

fig.for_each_trace(lambda t: t.update(
    mode='lines+markers+text',
    line=dict(width=4),
    marker=dict(size=12, line=dict(width=2, color='white')),
    textposition='top center',
    texttemplate='%{text:.1f}'
))

fig.update_layout(template='simple_white', hovermode=False)
fig.show()


file_name = f'./Vykonnost ekonomiky/gdp_per_capita_{today}.csv'
gdp_per_capita.to_csv(os.getcwd() + r'.\Vykonnost ekonomiky\gdp_per_capita_{}.csv'.format(today),index=True, header=True, encoding="utf-8-sig")

,Jednotka,Indikator,Krajina,2007,2008,2009,2010,2011,2012,2013
3289,PPS per capita,HDP podla trhovych cien,CZ,20692.0,21587.3,20826.8,21227.8,21786.4,21767.6,22410.8
3292,PPS per capita,HDP podla trhovych cien,Oblast Eura,27887.7,28385.1,26820.5,27628.3,28291.3,28275.1,28569.3
3299,PPS per capita,HDP podla trhovych cien,Staty EU,24679.2,25392.0,24226.7,25095.1,25876.8,25979.8,26253.5
3321,PPS per capita,HDP podla trhovych cien,SK,16696.1,18312.5,17321.0,19079.5,19526.5,19960.4,20266.6

In [3]:
###Celkovy hruby domaci produkt na krajinu

gdp_gross = eurostat.get_data_df('nama_10_gdp')
gdp_gross = gdp_gross[(gdp_gross['geo\\TIME_PERIOD'].isin(['SK', 'CZ','EU27_2020','EA']) & (gdp_gross['na_item'] == 'B1G') & (gdp_gross['unit'] == 'CP_MEUR'))]
gdp_gross = gdp_gross[['unit', 'geo\\TIME_PERIOD','2007','2008','2009','2010','2011','2012','2013']]
gdp_gross['geo\\TIME_PERIOD'] = gdp_gross['geo\\TIME_PERIOD'].replace({ 'EA': 'Oblast Eura','EU27_2020': 'Staty EU'})
gdp_gross = gdp_gross.rename(columns={'geo\\TIME_PERIOD': 'Krajina', 'unit' : 'Jednotka'})
gdp_gross['Jednotka'] = gdp_gross['Jednotka'].replace({'CP_MEUR': 'Sucasne ceny v mil. Eur'})


display(gdp_gross.tail(100))

gdp_2 = gdp_gross.melt(
    id_vars=['Krajina'],
    value_vars=['2007','2008','2009','2010','2011','2012','2013'],
    var_name='Year',
    value_name='Gross_GDP')

fig = px.line(
    gdp_2,
    x='Year',
    y='Gross_GDP',
    color='Krajina',
    markers=True,
    text='Gross_GDP',
    title='Hrube HDP – SK vs CZ (2007–2013)',
    labels={'Gross_GDP': 'Hrube HDP', 'Year': 'Rok'}
)

fig.for_each_trace(lambda t: t.update(
    mode='lines+markers+text',
    line=dict(width=4),
    marker=dict(size=12, line=dict(width=2, color='white')),
    textposition='top center',
    texttemplate='%{text:.1f}'  # 1 decimal
))

fig.update_layout(template='simple_white', hovermode=False)
fig.show()

file_name = f'./Vykonnost ekonomiky/gross_gdp_{today}.csv'
gdp_gross.to_csv(os.getcwd() + r'.\Vykonnost ekonomiky\gross_gdp_{}.csv'.format(today),index=True, header=True, encoding="utf-8-sig")

,Jednotka,Krajina,2007,2008,2009,2010,2011,2012,2013
13668,Sucasne ceny v mil. Eur,CZ,125780.7,146823.9,135019.6,144502.8,150546.4,147400.9,143926.7
13671,Sucasne ceny v mil. Eur,Oblast Eura,8305630.2,8560396.4,8352911.6,8562140.0,8801720.3,8820585.0,8902595.0
13678,Sucasne ceny v mil. Eur,Staty EU,9618990.8,9969685.0,9565406.4,9887370.1,10192240.6,10240555.4,10343438.8
13701,Sucasne ceny v mil. Eur,SK,50472.1,59534.7,57953.2,62293.1,64503.5,67018.9,67552.6

In [4]:
inflacia_hicp = eurostat.get_data_df('prc_hicp_aind')
inflacia_hicp = inflacia_hicp[(inflacia_hicp['geo\\TIME_PERIOD'].isin(['SK', 'CZ','EU27_2020','EA20']) & (inflacia_hicp['unit'] == 'RCH_A_AVG') & (inflacia_hicp['coicop'] == 'CP00'))]
inflacia_hicp = inflacia_hicp[['unit','coicop', 'geo\\TIME_PERIOD','2007','2008','2009','2010','2011','2012','2013']]

inflacia_hicp['geo\\TIME_PERIOD'] = inflacia_hicp['geo\\TIME_PERIOD'].replace({ 'EA20': 'Oblast Eura','EU27_2020': 'Staty EU'})
inflacia_hicp  = inflacia_hicp .rename(columns={'geo\\TIME_PERIOD': 'Krajina', 'unit' : 'Jednotka', 'coicop' : 'Polozky'})
inflacia_hicp ['Jednotka'] = inflacia_hicp ['Jednotka'].replace({'RCH_A_AVG': 'Rocna zmena v %'})
inflacia_hicp ['Polozky'] = inflacia_hicp ['Polozky'].replace({'CP00': 'Vsetky polozky'})

display(inflacia_hicp.tail(100))

infl_hicp = inflacia_hicp.melt(
    id_vars=['Krajina'],
    value_vars=['2007','2008','2009','2010','2011','2012','2013'],
    var_name='Year',
    value_name='Inflacia_perc')

fig = px.line(
    infl_hicp,
    x='Year',
    y='Inflacia_perc',
    color='Krajina',
    markers=True,
    text='Inflacia_perc',
    title='Inflacia HICP pre vsetky polozky – SK vs CZ (2007–2013)',
    labels={'Inflacia_perc': 'Inflacia v %', 'Year': 'Rok'}
)

fig.for_each_trace(lambda t: t.update(
    mode='lines+markers+text',
    line=dict(width=4),
    marker=dict(size=12, line=dict(width=2, color='white')),
    textposition='top center',
    texttemplate='%{text:.1f}'  # 1 decimal
))

fig.update_layout(template='simple_white', hovermode=False)
fig.show()

file_name = f'./Inflacia/inflacia_hicp_{today}.csv'
inflacia_hicp.to_csv(os.getcwd() + r'.\Inflacia\inflacia_hicp_{}.csv'.format(today),index=True, header=True, encoding="utf-8-sig")

,Jednotka,Polozky,Krajina,2007,2008,2009,2010,2011,2012,2013
17877,Rocna zmena v %,Vsetky polozky,CZ,2.9,6.3,0.6,1.2,2.2,3.5,1.4
17882,Rocna zmena v %,Vsetky polozky,Oblast Eura,2.2,3.4,0.3,1.6,2.7,2.5,1.4
17888,Rocna zmena v %,Vsetky polozky,Staty EU,2.4,3.7,0.8,1.8,2.9,2.6,1.3
17911,Rocna zmena v %,Vsetky polozky,SK,1.9,3.9,0.9,0.7,4.1,3.7,1.5

In [5]:
###Celkova miera nezamestnanosti 
nezamestnanost_celk = eurostat.get_data_df('une_rt_a')
nezamestnanost_celk = nezamestnanost_celk[(nezamestnanost_celk['geo\\TIME_PERIOD'].isin(['SK', 'CZ','EU27_2020','EA20']) & (nezamestnanost_celk['sex'] == 'T') & (nezamestnanost_celk['unit'] == 'PC_ACT') & (nezamestnanost_celk['age'] == 'Y15-74'))]
nezamestnanost_celk = nezamestnanost_celk[['unit','age','sex', 'geo\\TIME_PERIOD','2007','2008','2009','2010','2011','2012','2013']]
nezamestnanost_celk['geo\\TIME_PERIOD'] = nezamestnanost_celk['geo\\TIME_PERIOD'].replace({ 'EA20': 'Oblast Eura','EU27_2020': 'Staty EU'})

nezamestnanost_celk = nezamestnanost_celk.rename(columns={'geo\\TIME_PERIOD': 'Krajina', 'unit' : 'Jednotka', 'age' : 'Vekova skupina', 'sex' : 'Pohlavie'})
nezamestnanost_celk['Jednotka'] = nezamestnanost_celk['Jednotka'].replace({'PC_ACT': '% z pracujucej populacie'})
nezamestnanost_celk['Pohlavie'] = nezamestnanost_celk['Pohlavie'].replace({'T': 'Vsetky pohlavia'})
nezamestnanost_celk['Vekova skupina'] = nezamestnanost_celk['Vekova skupina'].replace({'Y15-74': '15-74 Rokov'})

display(nezamestnanost_celk.tail(100))

nezamest_total = nezamestnanost_celk.melt(
    id_vars=['Krajina'],
    value_vars=['2007','2008','2009','2010','2011','2012','2013'],
    var_name='Year',
    value_name='Nezamestnanost_celkova')

fig = px.line(
    nezamest_total,
    x='Year',
    y='Nezamestnanost_celkova',
    color='Krajina',
    markers=True,
    text='Nezamestnanost_celkova',
    title='Celkova miera nezamestnanosti v % z pracujucej populacie – SK vs CZ (2007–2013)',
    labels={'Nezamestnanost_celkova': 'Nezamestnanost v %', 'Year': 'Rok'}
)

fig.for_each_trace(lambda t: t.update(
    mode='lines+markers+text',
    line=dict(width=4),
    marker=dict(size=12, line=dict(width=2, color='white')),
    textposition='top center',
    texttemplate='%{text:.1f}'  # 1 decimal
))

fig.update_layout(template='simple_white', hovermode=False)
fig.show()

file_name = f'./Nezamestnanost/nezamestnanost_celk_{today}.csv'
nezamestnanost_celk.to_csv(os.getcwd() + r'.\Nezamestnanost\nezamestnanost_celk_{}.csv'.format(today),index=True, header=True, encoding="utf-8-sig")

,Jednotka,Vekova skupina,Pohlavie,Krajina,2007,2008,2009,2010,2011,2012,2013
746,% z pracujucej populacie,15-74 Rokov,Vsetky pohlavia,CZ,NaN,NaN,6.7,7.3,6.7,7.0,7.0
749,% z pracujucej populacie,15-74 Rokov,Vsetky pohlavia,Oblast Eura,NaN,NaN,9.7,10.3,10.3,11.5,12.2
753,% z pracujucej populacie,15-74 Rokov,Vsetky pohlavia,Staty EU,NaN,NaN,9.3,10.1,10.1,11.1,11.6
775,% z pracujucej populacie,15-74 Rokov,Vsetky pohlavia,SK,NaN,NaN,12.0,14.3,13.5,13.9,14.1

In [6]:
###Miera nezamestnanosti zien 
nezamestnanost_zien = eurostat.get_data_df('une_rt_a')
nezamestnanost_zien = nezamestnanost_zien[(nezamestnanost_zien['geo\\TIME_PERIOD'].isin(['SK', 'CZ','EU27_2020','EA20']) & (nezamestnanost_zien['sex'] == 'F') & (nezamestnanost_zien['unit'] == 'PC_ACT') & (nezamestnanost_zien['age'] == 'Y15-74'))]
nezamestnanost_zien = nezamestnanost_zien[['unit','age','sex', 'geo\\TIME_PERIOD','2007','2008','2009','2010','2011','2012','2013']]
nezamestnanost_zien['geo\\TIME_PERIOD'] = nezamestnanost_zien['geo\\TIME_PERIOD'].replace({ 'EA20': 'Oblast Eura','EU27_2020': 'Staty EU'})

nezamestnanost_zien = nezamestnanost_zien.rename(columns={'geo\\TIME_PERIOD': 'Krajina', 'unit' : 'Jednotka', 'age' : 'Vekova skupina', 'sex' : 'Pohlavie'})
nezamestnanost_zien['Jednotka'] = nezamestnanost_zien['Jednotka'].replace({'PC_ACT': '% z pracujucej populacie'})
nezamestnanost_zien['Pohlavie'] = nezamestnanost_zien['Pohlavie'].replace({'F': 'Zeny'})
nezamestnanost_zien['Vekova skupina'] = nezamestnanost_zien['Vekova skupina'].replace({'Y15-74': '15-74 Rokov'})

display(nezamestnanost_zien.tail(100))

nezamest_fem = nezamestnanost_zien.melt(
    id_vars=['Krajina'],
    value_vars=['2007','2008','2009','2010','2011','2012','2013'],
    var_name='Year',
    value_name='Nezamestnanost_zien')

fig = px.line(
    nezamest_fem,
    x='Year',
    y='Nezamestnanost_zien',
    color='Krajina',
    markers=True,
    text='Nezamestnanost_zien',
    title='Nezamestnanost zien z pracujucej populacie v% – SK vs CZ (2007–2013)',
    labels={'Nezamestnanost_zien': 'Nezamestnanost zien v %', 'Year': 'Rok'}
)

fig.for_each_trace(lambda t: t.update(
    mode='lines+markers+text',
    line=dict(width=4),
    marker=dict(size=12, line=dict(width=2, color='white')),
    textposition='top center',
    texttemplate='%{text:.1f}'  # 1 decimal
))

fig.update_layout(template='simple_white', hovermode=False)
fig.show()

file_name = f'./Nezamestnanost/nezamestnanost_zien_{today}.csv'
nezamestnanost_zien.to_csv(os.getcwd() + r'.\Nezamestnanost\nezamestnanost_zien_{}.csv'.format(today),index=True, header=True, encoding="utf-8-sig")

,Jednotka,Vekova skupina,Pohlavie,Krajina,2007,2008,2009,2010,2011,2012,2013
672,% z pracujucej populacie,15-74 Rokov,Zeny,CZ,NaN,NaN,7.7,8.5,7.9,8.2,8.3
675,% z pracujucej populacie,15-74 Rokov,Zeny,Oblast Eura,NaN,NaN,9.8,10.4,10.5,11.7,12.3
679,% z pracujucej populacie,15-74 Rokov,Zeny,Staty EU,NaN,NaN,9.5,10.2,10.3,11.2,11.7
701,% z pracujucej populacie,15-74 Rokov,Zeny,SK,NaN,NaN,13.0,14.8,13.8,14.7,14.7

In [7]:
###Miera nezamestnanosti mladych 15-24 rokov
nezamestnanost_mladych = eurostat.get_data_df('une_rt_a')
nezamestnanost_mladych = nezamestnanost_mladych[(nezamestnanost_mladych['geo\\TIME_PERIOD'].isin(['SK', 'CZ','EU27_2020','EA20']) & (nezamestnanost_mladych['sex'] == 'T') & (nezamestnanost_mladych['unit'] == 'PC_ACT') & (nezamestnanost_mladych['age'] == 'Y15-24'))]
nezamestnanost_mladych = nezamestnanost_mladych[['unit','age','sex', 'geo\\TIME_PERIOD','2007','2008','2009','2010','2011','2012','2013']]
nezamestnanost_mladych['geo\\TIME_PERIOD'] = nezamestnanost_mladych['geo\\TIME_PERIOD'].replace({ 'EA20': 'Oblast Eura','EU27_2020': 'Staty EU'})

nezamestnanost_mladych = nezamestnanost_mladych.rename(columns={'geo\\TIME_PERIOD': 'Krajina', 'unit' : 'Jednotka', 'age' : 'Vekova skupina', 'sex' : 'Pohlavie'})
nezamestnanost_mladych['Jednotka'] = nezamestnanost_mladych['Jednotka'].replace({'PC_ACT': '% z pracujucej populacie'})
nezamestnanost_mladych['Pohlavie'] = nezamestnanost_mladych['Pohlavie'].replace({'T': 'Vsetky pohlavia'})
nezamestnanost_mladych['Vekova skupina'] = nezamestnanost_mladych['Vekova skupina'].replace({'Y15-24': '15-24 Rokov'})

display(nezamestnanost_mladych.tail(100))

nezamest_yng = nezamestnanost_mladych.melt(
    id_vars=['Krajina'],
    value_vars=['2007','2008','2009','2010','2011','2012','2013'],
    var_name='Year',
    value_name='Nezamestnanost_zien')

fig = px.line(
    nezamest_yng,
    x='Year',
    y='Nezamestnanost_zien',
    color='Krajina',
    markers=True,
    text='Nezamestnanost_zien',
    title='Nezamestnanost mladych – SK vs CZ (2007–2013)',
    labels={'Nezamestnanost_zien': 'Nezamestnanost mladych vo veku 15-24 v %', 'Year': 'Rok'}
)

fig.for_each_trace(lambda t: t.update(
    mode='lines+markers+text',
    line=dict(width=4),
    marker=dict(size=12, line=dict(width=2, color='white')),
    textposition='top center',
    texttemplate='%{text:.1f}'  # 1 decimal
))

fig.update_layout(template='simple_white', hovermode=False)
fig.show()

file_name = f'./Nezamestnanost/nezamestnanost_mladych_{today}.csv'
nezamestnanost_mladych.to_csv(os.getcwd() + r'.\Nezamestnanost\nezamestnanost_mladych_{}.csv'.format(today),index=True, header=True, encoding="utf-8-sig")

,Jednotka,Vekova skupina,Pohlavie,Krajina,2007,2008,2009,2010,2011,2012,2013
80,% z pracujucej populacie,15-24 Rokov,Vsetky pohlavia,CZ,NaN,NaN,16.6,18.3,18.1,19.5,19.0
83,% z pracujucej populacie,15-24 Rokov,Vsetky pohlavia,Oblast Eura,NaN,NaN,21.3,22.1,22.1,24.3,25.2
87,% z pracujucej populacie,15-24 Rokov,Vsetky pohlavia,Staty EU,NaN,NaN,21.2,22.4,22.5,24.4,25.2
109,% z pracujucej populacie,15-24 Rokov,Vsetky pohlavia,SK,NaN,NaN,28.5,34.9,34.8,35.3,34.9

In [8]:
###Deficit/prebytok verejnych financií
statny_deficit = eurostat.get_data_df('gov_10dd_edpt1')
statny_deficit = statny_deficit[(statny_deficit['geo\\TIME_PERIOD'].isin(['SK', 'CZ','EU27_2020','EA20'])) & (statny_deficit['unit'] == 'PC_GDP') & (statny_deficit['sector'] == 'S13') & (statny_deficit['na_item'] == 'B9')]
statny_deficit = statny_deficit[['unit','sector','na_item', 'geo\\TIME_PERIOD','2007','2008','2009','2010','2011','2012','2013']]

statny_deficit['geo\\TIME_PERIOD'] = statny_deficit ['geo\\TIME_PERIOD'].replace({ 'EA20': 'Oblast Eura','EU27_2020': 'Staty EU'})
statny_deficit = statny_deficit.rename(columns={'geo\\TIME_PERIOD': 'Krajina', 'unit' : 'Jednotka', 'sector' : 'Statny sektor', 'na_item' : 'Polozka'})
statny_deficit['Jednotka'] = statny_deficit['Jednotka'].replace({'PC_GDP': '% z HDP'})
statny_deficit['Statny sektor'] = statny_deficit['Statny sektor'].replace({'S13': 'Vlada celkovo'})
statny_deficit['Polozka'] = statny_deficit['Polozka'].replace({'B9': 'Cisty dlh'})

file_name = f'./Fiskalna politika/statny_deficit_{today}.csv'
statny_deficit.to_csv(os.getcwd() + r'.\Fiskalna politika\statny_deficit_{}.csv'.format(today),index=True, header=True, encoding="utf-8-sig")
display(statny_deficit.tail(100))

statny_deficit = statny_deficit.melt(
    id_vars=['Krajina'],
    value_vars=['2007','2008','2009','2010','2011','2012','2013'],
    var_name='Rok',
    value_name='Statny_dlh')

fig = px.line(
    statny_deficit,
    x='Rok',
    y='Statny_dlh',
    color='Krajina',
    markers=True,
    text='Statny_dlh',
    title='Štátny deficit/prebytok – SK vs CZ (2007–2013)',
    labels={'Statny_dlh': 'Čistý dlh v % HDP', 'Rok': 'Rok'}
)

fig.for_each_trace(lambda t: t.update(
    mode='lines+markers+text',
    line=dict(width=4),
    marker=dict(size=12, line=dict(width=2, color='white')),
    textposition='top center',
    texttemplate='%{text:.1f}'
))

# Ensure all years show and in correct order
fig.update_xaxes(
    type='category',
    categoryorder='array',
    categoryarray=[str(y) for y in range(2007, 2014)]
)

# Horizontal Maastricht line across full width
fig.add_shape(
    type="line",
    xref="paper", yref="y",   # <<< key change
    x0=0, x1=1,               # span entire plotting area
    y0=-3, y1=-3,
    line=dict(width=3, color="red")
)
fig.add_annotation(
    x=0.01, y=-3, xref="paper", yref="y",
    text="Maastricht (−3 % HDP)",
    showarrow=False, yshift=-10,
    font=dict(size=12, color="red")
)

fig.update_layout(template='simple_white', hovermode=False)
fig.show()

,Jednotka,Statny sektor,Polozka,Krajina,2007,2008,2009,2010,2011,2012,2013
1496,% z HDP,Vlada celkovo,Cisty dlh,CZ,-0.7,-2.0,-5.5,-4.1,-2.7,-3.9,-1.3
1500,% z HDP,Vlada celkovo,Cisty dlh,Oblast Eura,-0.7,-2.3,-6.3,-6.3,-4.2,-3.9,-3.2
1504,% z HDP,Vlada celkovo,Cisty dlh,Staty EU,-0.6,-2.1,-6.1,-6.0,-4.1,-3.7,-3.1
1521,% z HDP,Vlada celkovo,Cisty dlh,SK,-2.3,-2.5,-8.2,-7.4,-4.4,-4.4,-2.9

In [9]:
gdp_eu_avg = eurostat.get_data_df('nama_10_pc')
gdp_eu_avg = gdp_eu_avg[(gdp_eu_avg['geo\\TIME_PERIOD'].isin(['SK', 'CZ','EU27_2020','EA']) & (gdp_eu_avg['na_item'] == 'B1GQ') & (gdp_eu_avg['unit'] == 'PC_EU27_2020_HAB_MEUR_CP'))]
gdp_eu_avg = gdp_eu_avg[['unit', 'geo\\TIME_PERIOD','2007','2008','2009','2010','2011','2012','2013']]
gdp_eu_avg['geo\\TIME_PERIOD'] = gdp_eu_avg['geo\\TIME_PERIOD'].replace({ 'EA': 'Oblast Eura','EU27_2020': 'Staty EU'})
gdp_eu_avg = gdp_eu_avg.rename(columns={'geo\\TIME_PERIOD': 'Krajina', 'unit' : 'Jednotka'})
gdp_eu_avg['Jednotka'] = gdp_eu_avg['Jednotka'].replace({'PC_EU27_2020_HAB_MEUR_CP': 'Pomer HDP na obyvatela k priemeru EU v %'})

gdp_3 = gdp_eu_avg.melt(
    id_vars=['Krajina'],
    value_vars=['2007','2008','2009','2010','2011','2012','2013'],
    var_name='Year',
    value_name='Gross_GDP')

fig = px.line(
    gdp_3,
    x='Year',
    y='Gross_GDP',
    color='Krajina',
    markers=True,
    text='Gross_GDP',
    title='Pomer HDP na obyvatela k priemeru EU vs CZ vs SK vs eurozona v % (2007–2013)',
    labels={'Gross_GDP': '%', 'Year': 'Rok'}
)

fig.for_each_trace(lambda x: x.update(
    mode='lines+markers+text',
    line=dict(width=4),
    marker=dict(size=12, line=dict(width=2, color='white')),
    textposition='top center',
    texttemplate='%{text:.1f}'  # 1 decimal
))

fig.update_layout(template='simple_white', hovermode=False)
fig.show()

file_name = f'./Ekonomicky rast a cykkly/gdp_eu_avg_{today}.csv'
gdp_eu_avg.to_csv(os.getcwd() + r'.\Ekonomicky rast a cykkly\gdp_eu_avg_{}.csv'.format(today),index=True, header=True, encoding="utf-8-sig")

In [10]:
eur_czk = eurostat.get_data_df('ert_bil_eur_m')
eur_czk = eur_czk[(eur_czk['currency\\TIME_PERIOD'].isin(['CZK']))]
eur_czk = eur_czk[['statinfo','currency\\TIME_PERIOD','2007-01','2007-02','2007-03','2007-04','2007-05','2007-06','2007-07','2007-08','2007-09','2007-10','2007-11','2007-12','2008-01','2008-02','2008-03','2008-04','2008-05','2008-06','2008-07','2008-08','2008-09','2008-10','2008-11','2008-12','2009-01','2009-02','2009-03','2009-04','2009-05','2009-06','2009-07','2009-08','2009-09','2009-10','2009-11','2009-12','2010-01','2010-02','2010-03','2010-04','2010-05','2010-06','2010-07','2010-08','2010-09','2010-10','2010-11','2010-12','2011-01','2011-02','2011-03','2011-04','2011-05','2011-06','2011-07','2011-08','2011-09','2011-10','2011-11','2011-12','2012-01','2012-02','2012-03','2012-04','2012-05','2012-06','2012-07','2012-08','2012-09','2012-10','2012-11','2012-12','2013-01','2013-02','2013-03','2013-04','2013-05','2013-06','2013-07','2013-08','2013-09','2013-10','2013-11','2013-12']]
eur_czk['statinfo'] = eur_czk['statinfo'].replace({ 'AVG': 'Mesacny priemer','END': 'Koniec mesiaca'})
eur_czk['currency\\TIME_PERIOD'] = eur_czk['currency\\TIME_PERIOD'].replace({ 'CZK': 'Ceska koruna (CZK)'})
display(eur_czk)

eur_czk_gph = eur_czk.melt(
    id_vars=['statinfo','currency\\TIME_PERIOD'],
    value_vars=['2007-01','2007-02','2007-03','2007-04','2007-05','2007-06','2007-07','2007-08','2007-09','2007-10','2007-11','2007-12','2008-01','2008-02','2008-03','2008-04','2008-05','2008-06','2008-07','2008-08','2008-09','2008-10','2008-11','2008-12','2009-01','2009-02','2009-03','2009-04','2009-05','2009-06','2009-07','2009-08','2009-09','2009-10','2009-11','2009-12','2010-01','2010-02','2010-03','2010-04','2010-05','2010-06','2010-07','2010-08','2010-09','2010-10','2010-11','2010-12','2011-01','2011-02','2011-03','2011-04','2011-05','2011-06','2011-07','2011-08','2011-09','2011-10','2011-11','2011-12','2012-01','2012-02','2012-03','2012-04','2012-05','2012-06','2012-07','2012-08','2012-09','2012-10','2012-11','2012-12','2013-01','2013-02','2013-03','2013-04','2013-05','2013-06','2013-07','2013-08','2013-09','2013-10','2013-11','2013-12'],
    var_name='Month',
    value_name='CZKperEUR')

fig = px.line(
    eur_czk_gph,
    x='Month',
    y='CZKperEUR',
    color='statinfo',
    markers=True,
    text='CZKperEUR',
    title='Mesacny priemer/Koniec mesiaca (2007–2013)',
    labels={'CZKperEUR': 'CZK za EUR', 'Month': 'Mesiac'}
)

fig.for_each_trace(lambda x: x.update(
    mode='lines+markers+text',
    line=dict(width=4),
    marker=dict(size=12, line=dict(width=2, color='white')),
    textposition='top center',
    texttemplate='%{text:.1f}'  # 1 decimal
))

fig.update_layout(template='simple_white', hovermode=False)
fig.show()

file_name = f'./Menova politika/eur_czk_{today}.csv'
eur_czk.to_csv(os.getcwd() + r'.\Menova politika\eur_czk_{}.csv'.format(today),index=True, header=True, encoding="utf-8-sig")

,statinfo,currency\TIME_PERIOD,2007-01,2007-02,2007-03,2007-04,2007-05,2007-06,2007-07,2007-08,...,2013-03,2013-04,2013-05,2013-06,2013-07,2013-08,2013-09,2013-10,2013-11,2013-12
8,Mesacny priemer,Ceska koruna (CZK),27.840,28.233,28.057,28.015,28.231,28.546,28.359,27.860,...,25.659,25.841,25.888,25.759,25.944,25.818,25.789,25.662,26.927,27.521
47,Koniec mesiaca,Ceska koruna (CZK),28.163,28.295,28.010,28.123,28.324,28.718,28.037,27.726,...,25.740,25.799,25.711,25.949,25.857,25.735,25.730,25.729,27.391,27.427

In [11]:
url = (
    "https://sdmx.oecd.org/public/rest/data/"
    "OECD.SDD.NAD,DSD_NAMAIN10@DF_TABLE1_EXPENDITURE,2.0/all"
    "?startPeriod=2007"
    "&endPeriod=2013"
    "&dimensionAtObservation=AllDimensions"
    "&format=csvfilewithlabels"
)

response = requests.get(url)
response.raise_for_status()

df = pd.read_csv(StringIO(response.text))

countries = ["SVK", "CZE"]
transactions = ["B1GQ", "P6", "P7"]   # HDP, export, import

df = df[
    (df["REF_AREA"].isin(countries)) &
    (df["TRANSACTION"].isin(transactions)) &
    (df["FREQ"] == "A")
].copy()

# Rok musí byť integer
df["TIME_PERIOD"] = df["TIME_PERIOD"].astype(int)

pivot_df = df.pivot_table(
    index=["REF_AREA", "TIME_PERIOD"],
    columns="TRANSACTION",
    values="OBS_VALUE"
).reset_index()

pivot_df = pivot_df.rename(columns={
    "REF_AREA": "country",
    "TIME_PERIOD": "year",
    "B1GQ": "GDP",
    "P6": "EXPORT",
    "P7": "IMPORT"
})

pivot_df["TRADE_BALANCE"] = pivot_df["EXPORT"] - pivot_df["IMPORT"]
pivot_df["OPENNESS_pct_GDP"] = (pivot_df["EXPORT"] + pivot_df["IMPORT"]) / pivot_df["GDP"] * 100

# Výsledný DataFrame
result_df = pivot_df.sort_values(["country", "year"]).reset_index(drop=True)

float_cols = ['EXPORT', 'IMPORT', 'TRADE_BALANCE', 'OPENNESS_pct_GDP']
result_df[float_cols] = result_df[float_cols].astype(np.float32).round(2)
result_df = result_df[['country','year','EXPORT', 'IMPORT', 'TRADE_BALANCE', 'OPENNESS_pct_GDP']]
file_name = f'./Medzinarodny obchod/import_export_{today}.csv'
result_df.to_csv(os.getcwd() + r'.\Medzinarodny obchod\import_export_{}.csv'.format(today),index=True, header=True, encoding="utf-8-sig")

trade_gph = result_df.copy()
trade_gph['year'] = trade_gph['year'].astype(str)  # peknejší x-axis

fig_trade = px.line(
    trade_gph,
    x='year',
    y='TRADE_BALANCE',
    color='country',
    markers=True,
    text='TRADE_BALANCE',
    title='Obchodná bilancia – CZE vs. SVK (2007–2013)',
    labels={
        'year': 'Rok',
        'TRADE_BALANCE': 'mil USD',
        'country': 'Krajina'
    }
)

fig_trade.for_each_trace(
    lambda tr: tr.update(
        mode='lines+markers+text',
        line=dict(width=4),
        marker=dict(size=12, line=dict(width=2, color='white')),
        textposition='top center',
        texttemplate='%{text:.0f}'  # celé čísla (sumy v mene)
    )
)

fig_trade.update_layout(
    template='simple_white',
    hovermode=False
)

open_gph = result_df.copy()
open_gph['year'] = open_gph['year'].astype(str)

fig_open = px.line(
    open_gph,
    x='year',
    y='OPENNESS_pct_GDP',
    color='country',
    markers=True,
    text='OPENNESS_pct_GDP',
    title='Miera otvorenosti ekonomiky – CZE vs. SVK (2007–2013)',
    labels={
        'year': 'Rok',
        'OPENNESS_pct_GDP': '% HDP',
        'country': 'Krajina'
    }
)

fig_open.for_each_trace(
    lambda tr: tr.update(
        mode='lines+markers+text',
        line=dict(width=4),
        marker=dict(size=12, line=dict(width=2, color='white')),
        textposition='top center',
        texttemplate='%{text:.1f}'  # 1 desatinné miesto pre %
    )
)

fig_open.update_layout(
    template='simple_white',
    hovermode=False
)


expimp_df = result_df.copy()
expimp_df['year'] = expimp_df['year'].astype(str)

# Melt → pripravíme 4 kombinácie: CZE/SVK × Export/Import
expimp_melt = expimp_df.melt(
    id_vars=['country', 'year'],
    value_vars=['EXPORT', 'IMPORT'],
    var_name='Type',
    value_name='Value'
)

# Pre krajšie texty
expimp_melt['Type'] = expimp_melt['Type'].replace({
    'EXPORT': 'Export',
    'IMPORT': 'Import'
})

# Spojíme do jednej legendy
expimp_melt['Legend'] = expimp_melt['country'] + " – " + expimp_melt['Type']

# Bar graf s klastrovaním vedľa seba
fig_bar = px.bar(
    expimp_melt,
    x='year',
    y='Value',
    color='Legend',
    barmode='group',
    text='Value',
    title='Export a import – CZE vs SVK (2007–2013)',
    labels={
        'year': 'Rok',
        'Value': 'mil USD',
        'Legend': 'Krajina – Tok'
    }
)

# Štýl podľa tvojej šablóny
fig_bar.for_each_trace(
    lambda tr: tr.update(
        texttemplate='%{text:.0f}',
        textposition='outside'
    )
)

fig_bar.update_layout(
    template='simple_white',
    hovermode=False,
    bargap=0.25,
    bargroupgap=0.05,
    uniformtext_minsize=8,
    uniformtext_mode='show'
)
fig_open.show()
fig_bar.show()
fig_trade.show()
display(result_df)

C:\Users\nyx3t\AppData\Local\Temp\ipykernel_47716\260292646.py:13: DtypeWarning:

Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.

TRANSACTION,country,year,EXPORT,IMPORT,TRADE_BALANCE,OPENNESS_pct_GDP
0,CZE,2007,769893.812500,737733.812500,32160.019531,116.440002
1,CZE,2008,796399.687500,755988.937500,40410.710938,115.000000
2,CZE,2009,712483.625000,665305.000000,47178.640625,105.910004
3,CZE,2010,814741.812500,762151.812500,52589.968750,117.580002
4,CZE,2011,889843.625000,821269.625000,68574.039062,125.430000
5,CZE,2012,937429.625000,856369.500000,81060.148438,132.110001
6,CZE,2013,950610.250000,865519.625000,85090.656250,133.039993
7,SVK,2007,56462.488281,57866.121094,-1403.619995,160.619995
8,SVK,2008,60227.359375,62961.019531,-2733.659912,157.539993
9,SVK,2009,50290.718750,51516.480469,-1225.760010,135.100006
10,SVK,2010,59469.761719,61089.691406,-1619.939941,149.529999
11,SVK,2011,67227.296875,67754.039062,-526.739990,161.630005
12,SVK,2012,74327.101562,70720.796875,3606.300049,169.850006
13,SVK,2013,77909.609375,74266.757812,3642.850098,175.979996

In [12]:
###Celkovy hruby domaci produkt na krajinu

gdp_perc = eurostat.get_data_df('nama_10_gdp')
gdp_perc = gdp_perc[(gdp_perc['geo\\TIME_PERIOD']).isin(['SK', 'CZ', 'EU27_2020']) & (gdp_perc['na_item'] == 'B1GQ') & (gdp_perc['unit'].isin(['CLV_I05']))]
gdp_perc = gdp_perc[['unit', 'geo\\TIME_PERIOD','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019','2020','2021','2022','2023','2024']]
gdp_perc['geo\\TIME_PERIOD'] = gdp_perc['geo\\TIME_PERIOD'].replace({ 'EA': 'Oblast Eura','EU27_2020': 'Staty EU'})
gdp_perc = gdp_perc.rename(columns={'geo\\TIME_PERIOD': 'Krajina', 'unit' : 'Jednotka'})
gdp_perc['Jednotka'] = gdp_perc['Jednotka'].replace({'CLV_I05': 'Referencny rok 2005'})

float_cols = ['2007','2008','2009','2010','2011','2012','2013']

gdp_perc[float_cols] = gdp_perc[float_cols].astype(np.float32).round(1)


display(gdp_perc.tail(100))

gdp_2 = gdp_perc.melt(
    id_vars=['Krajina'],
    value_vars=['2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019','2020','2021','2022','2023','2024'],
    var_name='Year',
    value_name='Gross_GDP')

fig = px.line(
    gdp_2,
    x='Year',
    y='Gross_GDP',
    color='Krajina',
    markers=True,
    text='Gross_GDP',
    title='Zmeny HDP v % pre CZ vs SK vs EU (ref.2005)',
    labels={'Gross_GDP': '%', 'Year': 'Rok'}
)

fig.for_each_trace(lambda t: t.update(
    mode='lines+markers+text',
    line=dict(width=4),
    marker=dict(size=12, line=dict(width=2, color='white')),
    textposition='top center',
    texttemplate='%{text:.1f}'  # 1 decimal
))

fig.update_layout(template='simple_white', hovermode=False)
fig.show()

file_name = f'./Ekonomicky rast a cykkly/gross_perc_2005_{today}.csv'
gdp_perc.to_csv(os.getcwd() + r'.\Ekonomicky rast a cykkly\gross_perc_2005_{}.csv'.format(today),index=True, header=True, encoding="utf-8-sig")

,Jednotka,Krajina,2005,2006,2007,2008,2009,2010,2011,2012,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
7862,Referencny rok 2005,CZ,100.0,106.623,112.500000,115.400002,109.900002,112.900002,114.900002,114.000000,...,122.260,125.415,131.904,135.637,140.474,133.022,138.381,142.321,142.389,144.145
7872,Referencny rok 2005,Staty EU,100.0,103.535,106.800003,107.400002,102.800003,105.000000,107.000000,106.199997,...,110.406,112.525,115.691,118.058,120.272,113.583,120.797,125.079,125.629,126.962
7893,Referencny rok 2005,SK,100.0,108.926,120.699997,127.199997,120.199997,128.300003,131.600006,133.699997,...,145.443,148.275,152.538,158.734,162.347,158.149,167.094,168.004,171.553,174.879

In [4]:
debt_perc = eurostat.get_data_df('gov_10q_ggdebt')
debt_perc  = debt_perc[(debt_perc['geo\\TIME_PERIOD']).isin(['SK', 'CZ', 'EU27_2020']) & (debt_perc['unit'].isin(['PC_GDP'])) & (debt_perc['na_item'].isin(['GD'])) & (debt_perc['sector'].isin(['S13']))]
debt_perc = debt_perc[['unit', 'geo\\TIME_PERIOD','2007-Q2','2007-Q3','2007-Q4','2008-Q1', '2008-Q2', '2008-Q3','2008-Q4','2009-Q1', 
                '2009-Q2', '2009-Q3','2009-Q4','2010-Q1', '2010-Q2', '2010-Q3','2010-Q4','2011-Q1', 
                '2011-Q2', '2011-Q3','2011-Q4','2012-Q1', '2012-Q2', '2012-Q3','2012-Q4','2013-Q1','2013-Q2', 
                '2013-Q3','2013-Q4', '2014-Q1','2014-Q2', '2014-Q3','2014-Q4','2015-Q1','2015-Q2', '2015-Q3',
                '2015-Q4','2016-Q1','2016-Q2', '2016-Q3','2016-Q4','2017-Q1','2017-Q2', '2017-Q3','2017-Q4',
                '2018-Q1','2018-Q2', '2018-Q3','2018-Q4','2019-Q1','2019-Q2', '2019-Q3','2019-Q4','2020-Q1',
                '2020-Q2', '2020-Q3','2020-Q4','2021-Q1','2021-Q2', '2021-Q3','2021-Q4','2022-Q1','2022-Q2', 
                '2022-Q3','2022-Q4','2023-Q1','2023-Q2', '2023-Q3','2023-Q4','2024-Q1','2024-Q2', '2024-Q3','2024-Q4', '2025-Q1','2025-Q2']]
debt_perc['geo\\TIME_PERIOD'] = debt_perc['geo\\TIME_PERIOD'].replace({'EU27_2020': 'Staty EU'})
debt_perc = debt_perc.rename(columns={'geo\\TIME_PERIOD': 'Krajina', 'unit' : 'Jednotka'})

float_cols = ['2007-Q2','2007-Q3','2007-Q4','2008-Q1', '2008-Q2', '2008-Q3','2008-Q4','2009-Q1', 
                '2009-Q2', '2009-Q3','2009-Q4','2010-Q1', '2010-Q2', '2010-Q3','2010-Q4','2011-Q1', 
                '2011-Q2', '2011-Q3','2011-Q4','2012-Q1', '2012-Q2', '2012-Q3','2012-Q4','2013-Q1','2013-Q2', 
                '2013-Q3','2013-Q4', '2014-Q1','2014-Q2', '2014-Q3','2014-Q4','2015-Q1','2015-Q2', '2015-Q3',
                '2015-Q4','2016-Q1','2016-Q2', '2016-Q3','2016-Q4','2017-Q1','2017-Q2', '2017-Q3','2017-Q4',
                '2018-Q1','2018-Q2', '2018-Q3','2018-Q4','2019-Q1','2019-Q2', '2019-Q3','2019-Q4','2020-Q1',
                '2020-Q2', '2020-Q3','2020-Q4','2021-Q1','2021-Q2', '2021-Q3','2021-Q4','2022-Q1','2022-Q2', 
                '2022-Q3','2022-Q4','2023-Q1','2023-Q2', '2023-Q3','2023-Q4','2024-Q1','2024-Q2', '2024-Q3','2024-Q4', '2025-Q1','2025-Q2']

debt_perc[float_cols] = debt_perc[float_cols].astype(np.float32).round(1)


display(debt_perc.tail(100))

debt_2 = debt_perc.melt(
    id_vars=['Krajina'],
    value_vars=['2007-Q2','2007-Q3','2007-Q4','2008-Q1', '2008-Q2', '2008-Q3','2008-Q4','2009-Q1', 
                '2009-Q2', '2009-Q3','2009-Q4','2010-Q1', '2010-Q2', '2010-Q3','2010-Q4','2011-Q1', 
                '2011-Q2', '2011-Q3','2011-Q4','2012-Q1', '2012-Q2', '2012-Q3','2012-Q4','2013-Q1','2013-Q2', 
                '2013-Q3','2013-Q4', '2014-Q1','2014-Q2', '2014-Q3','2014-Q4','2015-Q1','2015-Q2', '2015-Q3',
                '2015-Q4','2016-Q1','2016-Q2', '2016-Q3','2016-Q4','2017-Q1','2017-Q2', '2017-Q3','2017-Q4',
                '2018-Q1','2018-Q2', '2018-Q3','2018-Q4','2019-Q1','2019-Q2', '2019-Q3','2019-Q4','2020-Q1',
                '2020-Q2', '2020-Q3','2020-Q4','2021-Q1','2021-Q2', '2021-Q3','2021-Q4','2022-Q1','2022-Q2', 
                '2022-Q3','2022-Q4','2023-Q1','2023-Q2', '2023-Q3','2023-Q4','2024-Q1','2024-Q2', '2024-Q3','2024-Q4', '2025-Q1','2025-Q2'],
    var_name='Year',
    value_name='Gross_Debt')

fig = px.line(
    debt_2,
    x='Year',
    y='Gross_Debt',
    color='Krajina',
    markers=True,
    text='Gross_Debt',
    title='Hruby dlh v % HDP pre CZ vs SK vs EU',
    labels={'Gross_Debt': '% HDP', 'Year': 'Rok'})

fig.for_each_trace(lambda t: t.update(
    mode='lines+markers+text',
    line=dict(width=4),
    marker=dict(size=12, line=dict(width=2, color='white')),
    textposition='top center',
    texttemplate='%{text:.1f}'))

fig.update_layout(template='simple_white', hovermode=False)
fig.show()

file_name = f'./Fiskalna politika/debt_perc_2005_{today}.csv'
debt_perc.to_csv(os.getcwd() + r'.\Fiskalna politika\debt_perc_2005_{}.csv'.format(today),index=True, header=True, encoding="utf-8-sig")

,Jednotka,Krajina,2007-Q2,2007-Q3,2007-Q4,2008-Q1,2008-Q2,2008-Q3,2008-Q4,2009-Q1,...,2023-Q1,2023-Q2,2023-Q3,2023-Q4,2024-Q1,2024-Q2,2024-Q3,2024-Q4,2025-Q1,2025-Q2
5783,PC_GDP,CZ,27.700001,26.600000,27.299999,26.0,27.200001,26.9,28.200001,28.400000,...,42.799999,42.500000,42.700001,42.200001,43.099998,42.400002,43.400002,43.299999,43.299999,43.799999
5791,PC_GDP,Staty EU,64.900002,63.900002,62.400002,63.0,63.200001,63.0,65.099998,68.599998,...,82.199997,81.699997,81.199997,80.500000,81.000000,81.199997,81.300003,80.699997,81.500000,81.900002
5809,PC_GDP,SK,32.000000,31.100000,30.400000,27.4,26.600000,26.9,28.600000,29.600000,...,57.799999,59.299999,58.099998,55.799999,60.299999,60.200001,60.099998,59.700001,63.200001,62.900002

In [45]:
gini_coe = eurostat.get_data_df('ilc_di12b')
gini_coe  = gini_coe[(gini_coe['geo\\TIME_PERIOD']).isin(['SK', 'CZ'])]
gini_coe = gini_coe[['geo\\TIME_PERIOD','2007','2008','2009','2010','2011','2012','2013']]
gini_coe = gini_coe.rename(columns={'geo\\TIME_PERIOD': 'Krajina', 'indic_il' : 'GINI_Index'})
display(gini_coe.head(10))

gini_2 = gini_coe.melt(
    id_vars=['Krajina'],
    value_vars=['2007','2008','2009','2010','2011','2012','2013'],
    var_name='Year',
    value_name='GINI_Index')

fig = px.line(
    gini_2,
    x='Year',
    y='GINI_Index',
    color='Krajina',
    markers=True,
    text='GINI_Index',
    title='GINI Index pre CZ vs SK',
    labels={'Year': 'Rok'})

fig.for_each_trace(lambda t: t.update(
    mode='lines+markers+text',
    line=dict(width=4),
    marker=dict(size=12, line=dict(width=2, color='white')),
    textposition='top center',
    texttemplate='%{text:.1f}'))

fig.update_layout(template='simple_white', hovermode=False)
fig.show()

file_name = f'./Sociálno-ekonomické ukazovatele/gini_index_{today}.csv'
debt_perc.to_csv(os.getcwd() + r'.\Sociálno-ekonomické ukazovatele\gini_index_{}.csv'.format(today),index=True, header=True, encoding="utf-8-sig")

   Krajina  2007  2008  2009  2010  2011  2012  2013
6       CZ  44.9  44.1  43.7  43.8  44.1  44.5  44.1
41      SK  42.2  41.1  41.3  43.3  42.9  42.1  41.3

In [40]:
gini_coe = eurostat.get_data_df('ilc_di12b')
display(gini_coe.head(10))

,freq,indic_il,geo\TIME_PERIOD,2003,2004,2005,2006,2007,2008,2009,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,A,GINI_HND,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,47.5,45.3,44.1,42.7,43.1,40.3,38.8,NaN
1,A,GINI_HND,AT,46.2,43.9,45.0,45.0,46.3,46.3,46.8,...,47.6,47.3,47.5,46.3,47.6,46.7,47.5,47.4,47.4,47.8
2,A,GINI_HND,BE,50.8,48.6,50.6,48.7,46.7,48.0,46.6,...,48.0,48.7,48.5,46.9,46.2,46.1,47.6,46.6,46.3,46.7
3,A,GINI_HND,BG,NaN,NaN,NaN,52.8,50.4,49.7,46.4,...,51.6,52.8,55.2,54.8,54.5,53.4,54.0,52.4,52.9,53.8
4,A,GINI_HND,CH,NaN,NaN,NaN,NaN,46.5,48.1,48.1,...,50.3,51.8,52.2,52.4,54.1,54.5,55.8,55.5,54.7,54.8
5,A,GINI_HND,CY,NaN,NaN,38.2,37.7,37.3,39.0,39.4,...,49.9,50.2,48.6,47.6,48.1,47.3,47.2,42.8,41.8,42.7
6,A,GINI_HND,CZ,NaN,NaN,46.0,45.2,44.9,44.1,43.7,...,44.9,44.9,43.7,42.4,42.1,42.3,44.1,43.1,42.6,42.4
7,A,GINI_HND,DE,NaN,NaN,49.1,55.2,54.4,56.0,54.4,...,56.4,55.5,54.4,56.4,55.4,54.9,56.4,48.9,48.9,48.7
8,A,GINI_HND,DK,46.4,44.7,44.5,44.2,45.2,46.4,58.8,...,51.7,50.7,49.9,49.0,48.6,49.4,49.2,48.6,48.4,48.0
9,A,GINI_HND,EA,NaN,NaN,NaN,NaN,NaN,49.1,48.8,...,51.6,51.6,50.8,51.0,50.5,51.3,53.3,NaN,NaN,NaN